#!/usr/bin/env python3
"""Build docs/reference/glossary.md from every guide's Key-vocabulary table.

Two source formats exist (SITE_SPECIFICATION.md §6.3):
  - chapter guides:  | 中文 | English |            (translation pairs)
  - supplements:     | Term | Meaning |            (definitions)

Output: one alphabetized table — Term | 中文 | Meaning | Source(s) — with the
source linking to the originating guide's vocabulary section. Identical terms
are merged (sources accumulate); genuinely different glosses are kept side by
side in the Meaning cell.

Run manually after ingestion, and in CI before `mkdocs build`.
"""
from __future__ import annotations

import re
import sys
import unicodedata
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
OUT = DOCS / "reference" / "glossary.md"

SOURCE_DIRS = ["core", "supplements"]
VOCAB_HEADING_RE = re.compile(r"^##\s+(Key vocabulary.*?)\s*$")
CELL_SPLIT_RE = re.compile(r"(?<!\\)\|")  # don't split on escaped \|


def toc_slug(text: str) -> str:
    """Replicate python-markdown's default toc slugify (ASCII-only)."""
    text = unicodedata.normalize("NFKD", text).encode(
        "ascii", "ignore").decode("ascii")
    text = re.sub(r"[^\w\s-]", "", text).strip().lower()
    return re.sub(r"[-\s]+", "-", text)


def sort_key(term: str) -> str:
    """Alphabetize ignoring markdown markup and leading non-alphanumerics."""
    t = re.sub(r"[*`_]", "", term).strip()
    t = re.sub(r"^[^0-9A-Za-z一-鿿]+", "", t)
    return t.casefold()


def parse_front_matter_title(text: str) -> str | None:
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    m = re.search(r'^title:\s*"?([^"\n]+)"?\s*$', text[4:end], re.M)
    return m.group(1).strip() if m else None


def extract_vocab(path: Path) -> tuple[str, list[tuple[str, str, str]]] | None:
    """Return (section_anchor, rows) where rows are (term, zh, meaning)."""
    text = path.read_text(encoding="utf-8")
    lines = text.splitlines()
    heading_idx = anchor = None
    for i, line in enumerate(lines):
        m = VOCAB_HEADING_RE.match(line)
        if m:
            heading_idx, anchor = i, toc_slug(m.group(1))
            break
    if heading_idx is None:
        return None

    rows: list[tuple[str, str, str]] = []
    header: list[str] | None = None
    for line in lines[heading_idx + 1:]:
        s = line.strip()
        if s.startswith("## ") or (s.startswith("# ") and rows):
            break  # next section
        if not s.startswith("|"):
            continue
        cells = [c.strip() for c in CELL_SPLIT_RE.split(s.strip("|"))]
        if len(cells) < 2:
            continue
        if header is None:
            header = cells
            continue
        if set(cells[0]) <= {"-", ":", " "}:
            continue  # separator row
        if header[0].startswith("中文"):
            zh, term, meaning = cells[0], cells[1], ""
        else:
            term, zh, meaning = cells[0], "", cells[1]
        if term:
            rows.append((term, zh, meaning))
    return (anchor, rows) if rows else None


def main() -> int:
    entries: dict[str, dict] = {}  # normalized term -> merged entry
    n_sources = 0

    for dirname in SOURCE_DIRS:
        for path in sorted((DOCS / dirname).glob("*.md")):
            result = extract_vocab(path)
            if result is None:
                print(f"  WARN: no vocabulary table in {path.name}",
                      file=sys.stderr)
                continue
            anchor, rows = result
            title = parse_front_matter_title(
                path.read_text(encoding="utf-8")) or path.stem
            link = f"../{dirname}/{path.name.removesuffix('.md')}.md#{anchor}"
            source_md = f"[{title}]({link})"
            n_sources += 1

            for term, zh, meaning in rows:
                key = sort_key(term)
                e = entries.setdefault(
                    key, {"term": term, "zh": [], "meanings": [],
                          "sources": []})
                if zh and zh not in e["zh"]:
                    e["zh"].append(zh)
                if meaning and meaning not in e["meanings"]:
                    e["meanings"].append(meaning)
                if source_md not in e["sources"]:
                    e["sources"].append(source_md)

    lines = [
        "---",
        'title: "Glossary"',
        "search:",
        "  boost: 2",
        "---",
        "",
        "<!-- AUTO-GENERATED by scripts/build_glossary.py — do not edit by "
        "hand. Re-run the script after ingesting new guides. -->",
        "",
        "# Master glossary",
        "",
        f"Every term from all {n_sources} guides' Key-vocabulary tables, "
        "merged and alphabetized. Sources link to the originating guide's "
        "vocabulary section.",
        "",
        "| Term | 中文 | Meaning | Source(s) |",
        "|---|---|---|---|",
    ]
    for key in sorted(entries, key=str):
        e = entries[key]
        zh = "<br>".join(e["zh"]) or "—"
        meaning = "<br>".join(e["meanings"]) or "—"
        sources = " · ".join(e["sources"])
        lines.append(f"| {e['term']} | {zh} | {meaning} | {sources} |")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(entries)} terms "
          f"from {n_sources} guides.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
